name: integ

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    name: Java ${{ matrix.java }}
    strategy:
      matrix:
        java: [8, 11, 17]

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Install smithy cli
        run: brew tap aws/tap && brew install smithy-cli

      - name: Execute integration tests
        run: make test-all
        